os:
  - linux

language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules
    - "$HOME/google-cloud-sdk/"

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_32169b5b4df5_key -iv $encrypted_32169b5b4df5_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d

install:
  - npm install

script:
- node --version
- npm --version

after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - tar -xzf credentials.tar.gz
  - gcloud version
  - bash ./scripts/gcloud-auth.sh
  - bash ./scripts/gcloud-deploy.sh
